"""'df'

Revision ID: 250afebdf6c7
Revises: None
Create Date: 2016-09-21 09:52:32.264000

"""

# revision identifiers, used by Alembic.
revision = '250afebdf6c7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
