"""sdf

Revision ID: 26bb52179985
Revises: None
Create Date: 2016-09-16 07:55:33.050000

"""

# revision identifiers, used by Alembic.
revision = '26bb52179985'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('about', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'about')
    ### end Alembic commands ###
