"""sdf

Revision ID: 3b415355e96e
Revises: 26bb52179985
Create Date: 2016-09-16 08:08:29.594000

"""

# revision identifiers, used by Alembic.
revision = '3b415355e96e'
down_revision = '26bb52179985'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('cover', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'cover')
    ### end Alembic commands ###
