"""'f'

Revision ID: 49bd703e1129
Revises: 4f64bac8969d
Create Date: 2016-09-24 17:25:11.182000

"""

# revision identifiers, used by Alembic.
revision = '49bd703e1129'
down_revision = '4f64bac8969d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    ### end Alembic commands ###
