"""'sdf'

Revision ID: 49f8cfc8e3
Revises: 3b415355e96e
Create Date: 2016-09-18 16:35:10.886000

"""

# revision identifiers, used by Alembic.
revision = '49f8cfc8e3'
down_revision = '3b415355e96e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('type', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'type')
    ### end Alembic commands ###
